import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import Image from "next/image"
import Link from "next/link"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { AuthButtons } from "./_components/layout/navbar/auth-buttons"
import { ConvexProvider } from "./_components/layout/providers/convex-provider"
import { ThemeProvider } from "./_components/layout/providers/theme-provider"
import { ThemeDropdown } from "./_components/layout/theme-dropdown"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					<ThemeProvider>
						<ConvexProvider>
							<header className="flex justify-between items-center p-4 h-16">
								<Link href="/" aria-label="Home" className="inline-flex items-center gap-2">
									<Image src="/thiings/onigiri.png" alt="Macro Tracker" width={28} height={28} priority />
									<span className="text-base font-medium">Onigiri</span>
								</Link>

								<div className="flex items-center gap-4">
									<ThemeDropdown />

									<AuthButtons />
								</div>
							</header>

							{children}
						</ConvexProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
