import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs"
import { Button } from "@/components/shadcn/button"
import { ConvexProvider } from "./_components/layout/providers/convex-provider"
import { ThemeProvider } from "./_components/layout/providers/theme-provider"
import { ThemeDropdown } from "./_components/layout/theme-dropdown"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
					<ThemeProvider>
						<ConvexProvider>
							<header className="flex justify-end items-center p-4 gap-4 h-16">
								<ThemeDropdown />

								<SignedOut>
									<SignInButton>
										<Button variant="outline">Sign In</Button>
									</SignInButton>
									<SignUpButton>
										<Button>Sign Up</Button>
									</SignUpButton>
								</SignedOut>

								<SignedIn>
									<UserButton />
								</SignedIn>
							</header>

							{children}
						</ConvexProvider>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	)
}
